name: Deploy to EC2

on:
  push:
    branches: [ master ]     # ou o branch que você usa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install --omit=dev
      - run: npm run build

      - run: zip -r function.zip dist node_modules package.json package-lock.json

      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "function.zip"
          target: "~/html2pdf"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/html2pdf
            unzip -o function.zip
            pm2 delete html2pdf || true
            pm2 start dist/main.js --name html2pdf
            pm2 save
